#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : botocore
Version  : 1.18.18
Release  : 744
URL      : https://github.com/boto/botocore/archive/1.18.18/botocore-1.18.18.tar.gz
Source0  : https://github.com/boto/botocore/archive/1.18.18/botocore-1.18.18.tar.gz
Summary  : Low-level functionality of boto3
Group    : Development/Tools
License  : Apache-2.0 LGPL-2.1 MIT
Requires: botocore-license = %{version}-%{release}
Requires: botocore-python = %{version}-%{release}
Requires: botocore-python3 = %{version}-%{release}
Requires: jmespath
Requires: jsonschema
Requires: nose
Requires: python-dateutil
Requires: urllib3
Requires: wheel
BuildRequires : buildreq-distutils3
BuildRequires : jmespath
BuildRequires : jsonschema
BuildRequires : nose
BuildRequires : python-dateutil
BuildRequires : urllib3
BuildRequires : wheel

%description
A low-level interface to a growing number of Amazon Web Services. The botocore
package is the foundation for awscli as well as boto3.

%package license
Summary: license components for the botocore package.
Group: Default

%description license
license components for the botocore package.


%package python
Summary: python components for the botocore package.
Group: Default
Requires: botocore-python3 = %{version}-%{release}

%description python
python components for the botocore package.


%package python3
Summary: python3 components for the botocore package.
Group: Default
Requires: python3-core
Provides: pypi(botocore)
Requires: pypi(jmespath)
Requires: pypi(python_dateutil)
Requires: pypi(urllib3)

%description python3
python3 components for the botocore package.


%prep
%setup -q -n botocore-1.18.18
cd %{_builddir}/botocore-1.18.18

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1602879755
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/botocore
cp %{_builddir}/botocore-1.18.18/LICENSE.txt %{buildroot}/usr/share/package-licenses/botocore/598f87f072f66e2269dd6919292b2934dbb20492
cp %{_builddir}/botocore-1.18.18/NOTICE %{buildroot}/usr/share/package-licenses/botocore/d7a178c24429fa0e1bb6f6375b0db31677f1ac19
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/botocore/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/botocore/d7a178c24429fa0e1bb6f6375b0db31677f1ac19

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
