#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : botocore
Version  : 1.8.34
Release  : 161
URL      : https://pypi.python.org/packages/4f/91/71fbc5fe31474dc2b216290e5ac78e2bb2c9c5d735b07420d1e3ec877645/botocore-1.8.34.tar.gz
Source0  : https://pypi.python.org/packages/4f/91/71fbc5fe31474dc2b216290e5ac78e2bb2c9c5d735b07420d1e3ec877645/botocore-1.8.34.tar.gz
Summary  : Low-level, data-driven core of boto 3.
Group    : Development/Tools
License  : Apache-2.0
Requires: botocore-python3
Requires: botocore-python
Requires: docutils
Requires: jmespath
Requires: python-dateutil
BuildRequires : funcsigs-python
BuildRequires : jmespath-python
BuildRequires : nose-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dateutil
BuildRequires : python-dev
BuildRequires : python-mock-python
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python

%description
========

%package python
Summary: python components for the botocore package.
Group: Default
Requires: botocore-python3

%description python
python components for the botocore package.


%package python3
Summary: python3 components for the botocore package.
Group: Default
Requires: python3-core

%description python3
python3 components for the botocore package.


%prep
%setup -q -n botocore-1.8.34

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1516760886
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 || :
%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
